package com.example.demo.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScoreOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table score_order
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table score_order
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table score_order
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_order
     *
     * @mbggenerated
     */
    public ScoreOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_order
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_order
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_order
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_order
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_order
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_order
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_order
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_order
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_order
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_order
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table score_order
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("COMPANY_ID is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("COMPANY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Long value) {
            addCriterion("COMPANY_ID =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Long value) {
            addCriterion("COMPANY_ID <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Long value) {
            addCriterion("COMPANY_ID >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("COMPANY_ID >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Long value) {
            addCriterion("COMPANY_ID <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("COMPANY_ID <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Long> values) {
            addCriterion("COMPANY_ID in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Long> values) {
            addCriterion("COMPANY_ID not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Long value1, Long value2) {
            addCriterion("COMPANY_ID between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("COMPANY_ID not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andDelIsNull() {
            addCriterion("DEL is null");
            return (Criteria) this;
        }

        public Criteria andDelIsNotNull() {
            addCriterion("DEL is not null");
            return (Criteria) this;
        }

        public Criteria andDelEqualTo(Integer value) {
            addCriterion("DEL =", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotEqualTo(Integer value) {
            addCriterion("DEL <>", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThan(Integer value) {
            addCriterion("DEL >", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEL >=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThan(Integer value) {
            addCriterion("DEL <", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThanOrEqualTo(Integer value) {
            addCriterion("DEL <=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelIn(List<Integer> values) {
            addCriterion("DEL in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotIn(List<Integer> values) {
            addCriterion("DEL not in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelBetween(Integer value1, Integer value2) {
            addCriterion("DEL between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotBetween(Integer value1, Integer value2) {
            addCriterion("DEL not between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andBesorderIdIsNull() {
            addCriterion("BESORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andBesorderIdIsNotNull() {
            addCriterion("BESORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBesorderIdEqualTo(Long value) {
            addCriterion("BESORDER_ID =", value, "besorderId");
            return (Criteria) this;
        }

        public Criteria andBesorderIdNotEqualTo(Long value) {
            addCriterion("BESORDER_ID <>", value, "besorderId");
            return (Criteria) this;
        }

        public Criteria andBesorderIdGreaterThan(Long value) {
            addCriterion("BESORDER_ID >", value, "besorderId");
            return (Criteria) this;
        }

        public Criteria andBesorderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("BESORDER_ID >=", value, "besorderId");
            return (Criteria) this;
        }

        public Criteria andBesorderIdLessThan(Long value) {
            addCriterion("BESORDER_ID <", value, "besorderId");
            return (Criteria) this;
        }

        public Criteria andBesorderIdLessThanOrEqualTo(Long value) {
            addCriterion("BESORDER_ID <=", value, "besorderId");
            return (Criteria) this;
        }

        public Criteria andBesorderIdIn(List<Long> values) {
            addCriterion("BESORDER_ID in", values, "besorderId");
            return (Criteria) this;
        }

        public Criteria andBesorderIdNotIn(List<Long> values) {
            addCriterion("BESORDER_ID not in", values, "besorderId");
            return (Criteria) this;
        }

        public Criteria andBesorderIdBetween(Long value1, Long value2) {
            addCriterion("BESORDER_ID between", value1, value2, "besorderId");
            return (Criteria) this;
        }

        public Criteria andBesorderIdNotBetween(Long value1, Long value2) {
            addCriterion("BESORDER_ID not between", value1, value2, "besorderId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("PROJECT_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("PROJECT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Long value) {
            addCriterion("PROJECT_ID =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Long value) {
            addCriterion("PROJECT_ID <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Long value) {
            addCriterion("PROJECT_ID >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PROJECT_ID >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Long value) {
            addCriterion("PROJECT_ID <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Long value) {
            addCriterion("PROJECT_ID <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Long> values) {
            addCriterion("PROJECT_ID in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Long> values) {
            addCriterion("PROJECT_ID not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Long value1, Long value2) {
            addCriterion("PROJECT_ID between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Long value1, Long value2) {
            addCriterion("PROJECT_ID not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("CITY is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("CITY is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("CITY =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("CITY <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("CITY >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("CITY <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("CITY like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("CITY not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("CITY in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("CITY not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussIsNull() {
            addCriterion("FOREMAN_IS_DISCUSS is null");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussIsNotNull() {
            addCriterion("FOREMAN_IS_DISCUSS is not null");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussEqualTo(String value) {
            addCriterion("FOREMAN_IS_DISCUSS =", value, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussNotEqualTo(String value) {
            addCriterion("FOREMAN_IS_DISCUSS <>", value, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussGreaterThan(String value) {
            addCriterion("FOREMAN_IS_DISCUSS >", value, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussGreaterThanOrEqualTo(String value) {
            addCriterion("FOREMAN_IS_DISCUSS >=", value, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussLessThan(String value) {
            addCriterion("FOREMAN_IS_DISCUSS <", value, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussLessThanOrEqualTo(String value) {
            addCriterion("FOREMAN_IS_DISCUSS <=", value, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussLike(String value) {
            addCriterion("FOREMAN_IS_DISCUSS like", value, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussNotLike(String value) {
            addCriterion("FOREMAN_IS_DISCUSS not like", value, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussIn(List<String> values) {
            addCriterion("FOREMAN_IS_DISCUSS in", values, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussNotIn(List<String> values) {
            addCriterion("FOREMAN_IS_DISCUSS not in", values, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussBetween(String value1, String value2) {
            addCriterion("FOREMAN_IS_DISCUSS between", value1, value2, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanIsDiscussNotBetween(String value1, String value2) {
            addCriterion("FOREMAN_IS_DISCUSS not between", value1, value2, "foremanIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andForemanNumIsNull() {
            addCriterion("FOREMAN_NUM is null");
            return (Criteria) this;
        }

        public Criteria andForemanNumIsNotNull() {
            addCriterion("FOREMAN_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andForemanNumEqualTo(Integer value) {
            addCriterion("FOREMAN_NUM =", value, "foremanNum");
            return (Criteria) this;
        }

        public Criteria andForemanNumNotEqualTo(Integer value) {
            addCriterion("FOREMAN_NUM <>", value, "foremanNum");
            return (Criteria) this;
        }

        public Criteria andForemanNumGreaterThan(Integer value) {
            addCriterion("FOREMAN_NUM >", value, "foremanNum");
            return (Criteria) this;
        }

        public Criteria andForemanNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("FOREMAN_NUM >=", value, "foremanNum");
            return (Criteria) this;
        }

        public Criteria andForemanNumLessThan(Integer value) {
            addCriterion("FOREMAN_NUM <", value, "foremanNum");
            return (Criteria) this;
        }

        public Criteria andForemanNumLessThanOrEqualTo(Integer value) {
            addCriterion("FOREMAN_NUM <=", value, "foremanNum");
            return (Criteria) this;
        }

        public Criteria andForemanNumIn(List<Integer> values) {
            addCriterion("FOREMAN_NUM in", values, "foremanNum");
            return (Criteria) this;
        }

        public Criteria andForemanNumNotIn(List<Integer> values) {
            addCriterion("FOREMAN_NUM not in", values, "foremanNum");
            return (Criteria) this;
        }

        public Criteria andForemanNumBetween(Integer value1, Integer value2) {
            addCriterion("FOREMAN_NUM between", value1, value2, "foremanNum");
            return (Criteria) this;
        }

        public Criteria andForemanNumNotBetween(Integer value1, Integer value2) {
            addCriterion("FOREMAN_NUM not between", value1, value2, "foremanNum");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreIsNull() {
            addCriterion("FOREMAN_USER_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreIsNotNull() {
            addCriterion("FOREMAN_USER_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_USER_SCORE =", value, "foremanUserScore");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreNotEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_USER_SCORE <>", value, "foremanUserScore");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreGreaterThan(BigDecimal value) {
            addCriterion("FOREMAN_USER_SCORE >", value, "foremanUserScore");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_USER_SCORE >=", value, "foremanUserScore");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreLessThan(BigDecimal value) {
            addCriterion("FOREMAN_USER_SCORE <", value, "foremanUserScore");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_USER_SCORE <=", value, "foremanUserScore");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreIn(List<BigDecimal> values) {
            addCriterion("FOREMAN_USER_SCORE in", values, "foremanUserScore");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreNotIn(List<BigDecimal> values) {
            addCriterion("FOREMAN_USER_SCORE not in", values, "foremanUserScore");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FOREMAN_USER_SCORE between", value1, value2, "foremanUserScore");
            return (Criteria) this;
        }

        public Criteria andForemanUserScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FOREMAN_USER_SCORE not between", value1, value2, "foremanUserScore");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreIsNull() {
            addCriterion("FOREMAN_SUPERVISOR_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreIsNotNull() {
            addCriterion("FOREMAN_SUPERVISOR_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_SUPERVISOR_SCORE =", value, "foremanSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreNotEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_SUPERVISOR_SCORE <>", value, "foremanSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreGreaterThan(BigDecimal value) {
            addCriterion("FOREMAN_SUPERVISOR_SCORE >", value, "foremanSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_SUPERVISOR_SCORE >=", value, "foremanSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreLessThan(BigDecimal value) {
            addCriterion("FOREMAN_SUPERVISOR_SCORE <", value, "foremanSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_SUPERVISOR_SCORE <=", value, "foremanSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreIn(List<BigDecimal> values) {
            addCriterion("FOREMAN_SUPERVISOR_SCORE in", values, "foremanSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreNotIn(List<BigDecimal> values) {
            addCriterion("FOREMAN_SUPERVISOR_SCORE not in", values, "foremanSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FOREMAN_SUPERVISOR_SCORE between", value1, value2, "foremanSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andForemanSupervisorScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FOREMAN_SUPERVISOR_SCORE not between", value1, value2, "foremanSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreIsNull() {
            addCriterion("CENTER_FOREMAN_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreIsNotNull() {
            addCriterion("CENTER_FOREMAN_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreEqualTo(BigDecimal value) {
            addCriterion("CENTER_FOREMAN_SCORE =", value, "centerForemanScore");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreNotEqualTo(BigDecimal value) {
            addCriterion("CENTER_FOREMAN_SCORE <>", value, "centerForemanScore");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreGreaterThan(BigDecimal value) {
            addCriterion("CENTER_FOREMAN_SCORE >", value, "centerForemanScore");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CENTER_FOREMAN_SCORE >=", value, "centerForemanScore");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreLessThan(BigDecimal value) {
            addCriterion("CENTER_FOREMAN_SCORE <", value, "centerForemanScore");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CENTER_FOREMAN_SCORE <=", value, "centerForemanScore");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreIn(List<BigDecimal> values) {
            addCriterion("CENTER_FOREMAN_SCORE in", values, "centerForemanScore");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreNotIn(List<BigDecimal> values) {
            addCriterion("CENTER_FOREMAN_SCORE not in", values, "centerForemanScore");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CENTER_FOREMAN_SCORE between", value1, value2, "centerForemanScore");
            return (Criteria) this;
        }

        public Criteria andCenterForemanScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CENTER_FOREMAN_SCORE not between", value1, value2, "centerForemanScore");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresIsNull() {
            addCriterion("FOREMAN_TOTAL_SCORES is null");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresIsNotNull() {
            addCriterion("FOREMAN_TOTAL_SCORES is not null");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_TOTAL_SCORES =", value, "foremanTotalScores");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresNotEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_TOTAL_SCORES <>", value, "foremanTotalScores");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresGreaterThan(BigDecimal value) {
            addCriterion("FOREMAN_TOTAL_SCORES >", value, "foremanTotalScores");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_TOTAL_SCORES >=", value, "foremanTotalScores");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresLessThan(BigDecimal value) {
            addCriterion("FOREMAN_TOTAL_SCORES <", value, "foremanTotalScores");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FOREMAN_TOTAL_SCORES <=", value, "foremanTotalScores");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresIn(List<BigDecimal> values) {
            addCriterion("FOREMAN_TOTAL_SCORES in", values, "foremanTotalScores");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresNotIn(List<BigDecimal> values) {
            addCriterion("FOREMAN_TOTAL_SCORES not in", values, "foremanTotalScores");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FOREMAN_TOTAL_SCORES between", value1, value2, "foremanTotalScores");
            return (Criteria) this;
        }

        public Criteria andForemanTotalScoresNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FOREMAN_TOTAL_SCORES not between", value1, value2, "foremanTotalScores");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoIsNull() {
            addCriterion("FOREMAN_IS_DO is null");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoIsNotNull() {
            addCriterion("FOREMAN_IS_DO is not null");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoEqualTo(String value) {
            addCriterion("FOREMAN_IS_DO =", value, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoNotEqualTo(String value) {
            addCriterion("FOREMAN_IS_DO <>", value, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoGreaterThan(String value) {
            addCriterion("FOREMAN_IS_DO >", value, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoGreaterThanOrEqualTo(String value) {
            addCriterion("FOREMAN_IS_DO >=", value, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoLessThan(String value) {
            addCriterion("FOREMAN_IS_DO <", value, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoLessThanOrEqualTo(String value) {
            addCriterion("FOREMAN_IS_DO <=", value, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoLike(String value) {
            addCriterion("FOREMAN_IS_DO like", value, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoNotLike(String value) {
            addCriterion("FOREMAN_IS_DO not like", value, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoIn(List<String> values) {
            addCriterion("FOREMAN_IS_DO in", values, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoNotIn(List<String> values) {
            addCriterion("FOREMAN_IS_DO not in", values, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoBetween(String value1, String value2) {
            addCriterion("FOREMAN_IS_DO between", value1, value2, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanIsDoNotBetween(String value1, String value2) {
            addCriterion("FOREMAN_IS_DO not between", value1, value2, "foremanIsDo");
            return (Criteria) this;
        }

        public Criteria andForemanTimeIsNull() {
            addCriterion("FOREMAN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andForemanTimeIsNotNull() {
            addCriterion("FOREMAN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andForemanTimeEqualTo(Date value) {
            addCriterion("FOREMAN_TIME =", value, "foremanTime");
            return (Criteria) this;
        }

        public Criteria andForemanTimeNotEqualTo(Date value) {
            addCriterion("FOREMAN_TIME <>", value, "foremanTime");
            return (Criteria) this;
        }

        public Criteria andForemanTimeGreaterThan(Date value) {
            addCriterion("FOREMAN_TIME >", value, "foremanTime");
            return (Criteria) this;
        }

        public Criteria andForemanTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FOREMAN_TIME >=", value, "foremanTime");
            return (Criteria) this;
        }

        public Criteria andForemanTimeLessThan(Date value) {
            addCriterion("FOREMAN_TIME <", value, "foremanTime");
            return (Criteria) this;
        }

        public Criteria andForemanTimeLessThanOrEqualTo(Date value) {
            addCriterion("FOREMAN_TIME <=", value, "foremanTime");
            return (Criteria) this;
        }

        public Criteria andForemanTimeIn(List<Date> values) {
            addCriterion("FOREMAN_TIME in", values, "foremanTime");
            return (Criteria) this;
        }

        public Criteria andForemanTimeNotIn(List<Date> values) {
            addCriterion("FOREMAN_TIME not in", values, "foremanTime");
            return (Criteria) this;
        }

        public Criteria andForemanTimeBetween(Date value1, Date value2) {
            addCriterion("FOREMAN_TIME between", value1, value2, "foremanTime");
            return (Criteria) this;
        }

        public Criteria andForemanTimeNotBetween(Date value1, Date value2) {
            addCriterion("FOREMAN_TIME not between", value1, value2, "foremanTime");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeIsNull() {
            addCriterion("FOREMAN_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeIsNotNull() {
            addCriterion("FOREMAN_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeEqualTo(Date value) {
            addCriterion("FOREMAN_UPDATE_TIME =", value, "foremanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeNotEqualTo(Date value) {
            addCriterion("FOREMAN_UPDATE_TIME <>", value, "foremanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeGreaterThan(Date value) {
            addCriterion("FOREMAN_UPDATE_TIME >", value, "foremanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FOREMAN_UPDATE_TIME >=", value, "foremanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeLessThan(Date value) {
            addCriterion("FOREMAN_UPDATE_TIME <", value, "foremanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("FOREMAN_UPDATE_TIME <=", value, "foremanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeIn(List<Date> values) {
            addCriterion("FOREMAN_UPDATE_TIME in", values, "foremanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeNotIn(List<Date> values) {
            addCriterion("FOREMAN_UPDATE_TIME not in", values, "foremanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("FOREMAN_UPDATE_TIME between", value1, value2, "foremanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andForemanUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("FOREMAN_UPDATE_TIME not between", value1, value2, "foremanUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussIsNull() {
            addCriterion("DESIGN_IS_DISCUSS is null");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussIsNotNull() {
            addCriterion("DESIGN_IS_DISCUSS is not null");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussEqualTo(String value) {
            addCriterion("DESIGN_IS_DISCUSS =", value, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussNotEqualTo(String value) {
            addCriterion("DESIGN_IS_DISCUSS <>", value, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussGreaterThan(String value) {
            addCriterion("DESIGN_IS_DISCUSS >", value, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_IS_DISCUSS >=", value, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussLessThan(String value) {
            addCriterion("DESIGN_IS_DISCUSS <", value, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_IS_DISCUSS <=", value, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussLike(String value) {
            addCriterion("DESIGN_IS_DISCUSS like", value, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussNotLike(String value) {
            addCriterion("DESIGN_IS_DISCUSS not like", value, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussIn(List<String> values) {
            addCriterion("DESIGN_IS_DISCUSS in", values, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussNotIn(List<String> values) {
            addCriterion("DESIGN_IS_DISCUSS not in", values, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussBetween(String value1, String value2) {
            addCriterion("DESIGN_IS_DISCUSS between", value1, value2, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignIsDiscussNotBetween(String value1, String value2) {
            addCriterion("DESIGN_IS_DISCUSS not between", value1, value2, "designIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andDesignNumIsNull() {
            addCriterion("DESIGN_NUM is null");
            return (Criteria) this;
        }

        public Criteria andDesignNumIsNotNull() {
            addCriterion("DESIGN_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andDesignNumEqualTo(Integer value) {
            addCriterion("DESIGN_NUM =", value, "designNum");
            return (Criteria) this;
        }

        public Criteria andDesignNumNotEqualTo(Integer value) {
            addCriterion("DESIGN_NUM <>", value, "designNum");
            return (Criteria) this;
        }

        public Criteria andDesignNumGreaterThan(Integer value) {
            addCriterion("DESIGN_NUM >", value, "designNum");
            return (Criteria) this;
        }

        public Criteria andDesignNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("DESIGN_NUM >=", value, "designNum");
            return (Criteria) this;
        }

        public Criteria andDesignNumLessThan(Integer value) {
            addCriterion("DESIGN_NUM <", value, "designNum");
            return (Criteria) this;
        }

        public Criteria andDesignNumLessThanOrEqualTo(Integer value) {
            addCriterion("DESIGN_NUM <=", value, "designNum");
            return (Criteria) this;
        }

        public Criteria andDesignNumIn(List<Integer> values) {
            addCriterion("DESIGN_NUM in", values, "designNum");
            return (Criteria) this;
        }

        public Criteria andDesignNumNotIn(List<Integer> values) {
            addCriterion("DESIGN_NUM not in", values, "designNum");
            return (Criteria) this;
        }

        public Criteria andDesignNumBetween(Integer value1, Integer value2) {
            addCriterion("DESIGN_NUM between", value1, value2, "designNum");
            return (Criteria) this;
        }

        public Criteria andDesignNumNotBetween(Integer value1, Integer value2) {
            addCriterion("DESIGN_NUM not between", value1, value2, "designNum");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreIsNull() {
            addCriterion("DESIGN_USER_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreIsNotNull() {
            addCriterion("DESIGN_USER_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreEqualTo(BigDecimal value) {
            addCriterion("DESIGN_USER_SCORE =", value, "designUserScore");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreNotEqualTo(BigDecimal value) {
            addCriterion("DESIGN_USER_SCORE <>", value, "designUserScore");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreGreaterThan(BigDecimal value) {
            addCriterion("DESIGN_USER_SCORE >", value, "designUserScore");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DESIGN_USER_SCORE >=", value, "designUserScore");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreLessThan(BigDecimal value) {
            addCriterion("DESIGN_USER_SCORE <", value, "designUserScore");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DESIGN_USER_SCORE <=", value, "designUserScore");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreIn(List<BigDecimal> values) {
            addCriterion("DESIGN_USER_SCORE in", values, "designUserScore");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreNotIn(List<BigDecimal> values) {
            addCriterion("DESIGN_USER_SCORE not in", values, "designUserScore");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DESIGN_USER_SCORE between", value1, value2, "designUserScore");
            return (Criteria) this;
        }

        public Criteria andDesignUserScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DESIGN_USER_SCORE not between", value1, value2, "designUserScore");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreIsNull() {
            addCriterion("DESIGN_SUPERVISOR_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreIsNotNull() {
            addCriterion("DESIGN_SUPERVISOR_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreEqualTo(BigDecimal value) {
            addCriterion("DESIGN_SUPERVISOR_SCORE =", value, "designSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreNotEqualTo(BigDecimal value) {
            addCriterion("DESIGN_SUPERVISOR_SCORE <>", value, "designSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreGreaterThan(BigDecimal value) {
            addCriterion("DESIGN_SUPERVISOR_SCORE >", value, "designSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DESIGN_SUPERVISOR_SCORE >=", value, "designSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreLessThan(BigDecimal value) {
            addCriterion("DESIGN_SUPERVISOR_SCORE <", value, "designSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DESIGN_SUPERVISOR_SCORE <=", value, "designSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreIn(List<BigDecimal> values) {
            addCriterion("DESIGN_SUPERVISOR_SCORE in", values, "designSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreNotIn(List<BigDecimal> values) {
            addCriterion("DESIGN_SUPERVISOR_SCORE not in", values, "designSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DESIGN_SUPERVISOR_SCORE between", value1, value2, "designSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andDesignSupervisorScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DESIGN_SUPERVISOR_SCORE not between", value1, value2, "designSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreIsNull() {
            addCriterion("DESIGN_CENTER_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreIsNotNull() {
            addCriterion("DESIGN_CENTER_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreEqualTo(BigDecimal value) {
            addCriterion("DESIGN_CENTER_SCORE =", value, "designCenterScore");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreNotEqualTo(BigDecimal value) {
            addCriterion("DESIGN_CENTER_SCORE <>", value, "designCenterScore");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreGreaterThan(BigDecimal value) {
            addCriterion("DESIGN_CENTER_SCORE >", value, "designCenterScore");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DESIGN_CENTER_SCORE >=", value, "designCenterScore");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreLessThan(BigDecimal value) {
            addCriterion("DESIGN_CENTER_SCORE <", value, "designCenterScore");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DESIGN_CENTER_SCORE <=", value, "designCenterScore");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreIn(List<BigDecimal> values) {
            addCriterion("DESIGN_CENTER_SCORE in", values, "designCenterScore");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreNotIn(List<BigDecimal> values) {
            addCriterion("DESIGN_CENTER_SCORE not in", values, "designCenterScore");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DESIGN_CENTER_SCORE between", value1, value2, "designCenterScore");
            return (Criteria) this;
        }

        public Criteria andDesignCenterScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DESIGN_CENTER_SCORE not between", value1, value2, "designCenterScore");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresIsNull() {
            addCriterion("DESIGN_TOTAL_SCORES is null");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresIsNotNull() {
            addCriterion("DESIGN_TOTAL_SCORES is not null");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresEqualTo(BigDecimal value) {
            addCriterion("DESIGN_TOTAL_SCORES =", value, "designTotalScores");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresNotEqualTo(BigDecimal value) {
            addCriterion("DESIGN_TOTAL_SCORES <>", value, "designTotalScores");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresGreaterThan(BigDecimal value) {
            addCriterion("DESIGN_TOTAL_SCORES >", value, "designTotalScores");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DESIGN_TOTAL_SCORES >=", value, "designTotalScores");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresLessThan(BigDecimal value) {
            addCriterion("DESIGN_TOTAL_SCORES <", value, "designTotalScores");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DESIGN_TOTAL_SCORES <=", value, "designTotalScores");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresIn(List<BigDecimal> values) {
            addCriterion("DESIGN_TOTAL_SCORES in", values, "designTotalScores");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresNotIn(List<BigDecimal> values) {
            addCriterion("DESIGN_TOTAL_SCORES not in", values, "designTotalScores");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DESIGN_TOTAL_SCORES between", value1, value2, "designTotalScores");
            return (Criteria) this;
        }

        public Criteria andDesignTotalScoresNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DESIGN_TOTAL_SCORES not between", value1, value2, "designTotalScores");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoIsNull() {
            addCriterion("DESIGN_IS_CENTER_DO is null");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoIsNotNull() {
            addCriterion("DESIGN_IS_CENTER_DO is not null");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoEqualTo(String value) {
            addCriterion("DESIGN_IS_CENTER_DO =", value, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoNotEqualTo(String value) {
            addCriterion("DESIGN_IS_CENTER_DO <>", value, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoGreaterThan(String value) {
            addCriterion("DESIGN_IS_CENTER_DO >", value, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_IS_CENTER_DO >=", value, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoLessThan(String value) {
            addCriterion("DESIGN_IS_CENTER_DO <", value, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_IS_CENTER_DO <=", value, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoLike(String value) {
            addCriterion("DESIGN_IS_CENTER_DO like", value, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoNotLike(String value) {
            addCriterion("DESIGN_IS_CENTER_DO not like", value, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoIn(List<String> values) {
            addCriterion("DESIGN_IS_CENTER_DO in", values, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoNotIn(List<String> values) {
            addCriterion("DESIGN_IS_CENTER_DO not in", values, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoBetween(String value1, String value2) {
            addCriterion("DESIGN_IS_CENTER_DO between", value1, value2, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignIsCenterDoNotBetween(String value1, String value2) {
            addCriterion("DESIGN_IS_CENTER_DO not between", value1, value2, "designIsCenterDo");
            return (Criteria) this;
        }

        public Criteria andDesignTimeIsNull() {
            addCriterion("DESIGN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDesignTimeIsNotNull() {
            addCriterion("DESIGN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDesignTimeEqualTo(Date value) {
            addCriterion("DESIGN_TIME =", value, "designTime");
            return (Criteria) this;
        }

        public Criteria andDesignTimeNotEqualTo(Date value) {
            addCriterion("DESIGN_TIME <>", value, "designTime");
            return (Criteria) this;
        }

        public Criteria andDesignTimeGreaterThan(Date value) {
            addCriterion("DESIGN_TIME >", value, "designTime");
            return (Criteria) this;
        }

        public Criteria andDesignTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DESIGN_TIME >=", value, "designTime");
            return (Criteria) this;
        }

        public Criteria andDesignTimeLessThan(Date value) {
            addCriterion("DESIGN_TIME <", value, "designTime");
            return (Criteria) this;
        }

        public Criteria andDesignTimeLessThanOrEqualTo(Date value) {
            addCriterion("DESIGN_TIME <=", value, "designTime");
            return (Criteria) this;
        }

        public Criteria andDesignTimeIn(List<Date> values) {
            addCriterion("DESIGN_TIME in", values, "designTime");
            return (Criteria) this;
        }

        public Criteria andDesignTimeNotIn(List<Date> values) {
            addCriterion("DESIGN_TIME not in", values, "designTime");
            return (Criteria) this;
        }

        public Criteria andDesignTimeBetween(Date value1, Date value2) {
            addCriterion("DESIGN_TIME between", value1, value2, "designTime");
            return (Criteria) this;
        }

        public Criteria andDesignTimeNotBetween(Date value1, Date value2) {
            addCriterion("DESIGN_TIME not between", value1, value2, "designTime");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeIsNull() {
            addCriterion("DESIGN_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeIsNotNull() {
            addCriterion("DESIGN_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeEqualTo(Date value) {
            addCriterion("DESIGN_UPDATE_TIME =", value, "designUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeNotEqualTo(Date value) {
            addCriterion("DESIGN_UPDATE_TIME <>", value, "designUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeGreaterThan(Date value) {
            addCriterion("DESIGN_UPDATE_TIME >", value, "designUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DESIGN_UPDATE_TIME >=", value, "designUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeLessThan(Date value) {
            addCriterion("DESIGN_UPDATE_TIME <", value, "designUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("DESIGN_UPDATE_TIME <=", value, "designUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeIn(List<Date> values) {
            addCriterion("DESIGN_UPDATE_TIME in", values, "designUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeNotIn(List<Date> values) {
            addCriterion("DESIGN_UPDATE_TIME not in", values, "designUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("DESIGN_UPDATE_TIME between", value1, value2, "designUpdateTime");
            return (Criteria) this;
        }

        public Criteria andDesignUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("DESIGN_UPDATE_TIME not between", value1, value2, "designUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNull() {
            addCriterion("REMARK1 is null");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNotNull() {
            addCriterion("REMARK1 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark1EqualTo(String value) {
            addCriterion("REMARK1 =", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotEqualTo(String value) {
            addCriterion("REMARK1 <>", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThan(String value) {
            addCriterion("REMARK1 >", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThanOrEqualTo(String value) {
            addCriterion("REMARK1 >=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThan(String value) {
            addCriterion("REMARK1 <", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThanOrEqualTo(String value) {
            addCriterion("REMARK1 <=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Like(String value) {
            addCriterion("REMARK1 like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotLike(String value) {
            addCriterion("REMARK1 not like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1In(List<String> values) {
            addCriterion("REMARK1 in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotIn(List<String> values) {
            addCriterion("REMARK1 not in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Between(String value1, String value2) {
            addCriterion("REMARK1 between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotBetween(String value1, String value2) {
            addCriterion("REMARK1 not between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNull() {
            addCriterion("REMARK2 is null");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNotNull() {
            addCriterion("REMARK2 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark2EqualTo(String value) {
            addCriterion("REMARK2 =", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotEqualTo(String value) {
            addCriterion("REMARK2 <>", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThan(String value) {
            addCriterion("REMARK2 >", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThanOrEqualTo(String value) {
            addCriterion("REMARK2 >=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThan(String value) {
            addCriterion("REMARK2 <", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThanOrEqualTo(String value) {
            addCriterion("REMARK2 <=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Like(String value) {
            addCriterion("REMARK2 like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotLike(String value) {
            addCriterion("REMARK2 not like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2In(List<String> values) {
            addCriterion("REMARK2 in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotIn(List<String> values) {
            addCriterion("REMARK2 not in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Between(String value1, String value2) {
            addCriterion("REMARK2 between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotBetween(String value1, String value2) {
            addCriterion("REMARK2 not between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussIsNull() {
            addCriterion("SUPERVISOR_IS_DISCUSS is null");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussIsNotNull() {
            addCriterion("SUPERVISOR_IS_DISCUSS is not null");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussEqualTo(String value) {
            addCriterion("SUPERVISOR_IS_DISCUSS =", value, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussNotEqualTo(String value) {
            addCriterion("SUPERVISOR_IS_DISCUSS <>", value, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussGreaterThan(String value) {
            addCriterion("SUPERVISOR_IS_DISCUSS >", value, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussGreaterThanOrEqualTo(String value) {
            addCriterion("SUPERVISOR_IS_DISCUSS >=", value, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussLessThan(String value) {
            addCriterion("SUPERVISOR_IS_DISCUSS <", value, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussLessThanOrEqualTo(String value) {
            addCriterion("SUPERVISOR_IS_DISCUSS <=", value, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussLike(String value) {
            addCriterion("SUPERVISOR_IS_DISCUSS like", value, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussNotLike(String value) {
            addCriterion("SUPERVISOR_IS_DISCUSS not like", value, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussIn(List<String> values) {
            addCriterion("SUPERVISOR_IS_DISCUSS in", values, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussNotIn(List<String> values) {
            addCriterion("SUPERVISOR_IS_DISCUSS not in", values, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussBetween(String value1, String value2) {
            addCriterion("SUPERVISOR_IS_DISCUSS between", value1, value2, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDiscussNotBetween(String value1, String value2) {
            addCriterion("SUPERVISOR_IS_DISCUSS not between", value1, value2, "supervisorIsDiscuss");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumIsNull() {
            addCriterion("SUPERVISOR_NUM is null");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumIsNotNull() {
            addCriterion("SUPERVISOR_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumEqualTo(Integer value) {
            addCriterion("SUPERVISOR_NUM =", value, "supervisorNum");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumNotEqualTo(Integer value) {
            addCriterion("SUPERVISOR_NUM <>", value, "supervisorNum");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumGreaterThan(Integer value) {
            addCriterion("SUPERVISOR_NUM >", value, "supervisorNum");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("SUPERVISOR_NUM >=", value, "supervisorNum");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumLessThan(Integer value) {
            addCriterion("SUPERVISOR_NUM <", value, "supervisorNum");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumLessThanOrEqualTo(Integer value) {
            addCriterion("SUPERVISOR_NUM <=", value, "supervisorNum");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumIn(List<Integer> values) {
            addCriterion("SUPERVISOR_NUM in", values, "supervisorNum");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumNotIn(List<Integer> values) {
            addCriterion("SUPERVISOR_NUM not in", values, "supervisorNum");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumBetween(Integer value1, Integer value2) {
            addCriterion("SUPERVISOR_NUM between", value1, value2, "supervisorNum");
            return (Criteria) this;
        }

        public Criteria andSupervisorNumNotBetween(Integer value1, Integer value2) {
            addCriterion("SUPERVISOR_NUM not between", value1, value2, "supervisorNum");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreIsNull() {
            addCriterion("SUPERVISOR_USER_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreIsNotNull() {
            addCriterion("SUPERVISOR_USER_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreEqualTo(BigDecimal value) {
            addCriterion("SUPERVISOR_USER_SCORE =", value, "supervisorUserScore");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreNotEqualTo(BigDecimal value) {
            addCriterion("SUPERVISOR_USER_SCORE <>", value, "supervisorUserScore");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreGreaterThan(BigDecimal value) {
            addCriterion("SUPERVISOR_USER_SCORE >", value, "supervisorUserScore");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUPERVISOR_USER_SCORE >=", value, "supervisorUserScore");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreLessThan(BigDecimal value) {
            addCriterion("SUPERVISOR_USER_SCORE <", value, "supervisorUserScore");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUPERVISOR_USER_SCORE <=", value, "supervisorUserScore");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreIn(List<BigDecimal> values) {
            addCriterion("SUPERVISOR_USER_SCORE in", values, "supervisorUserScore");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreNotIn(List<BigDecimal> values) {
            addCriterion("SUPERVISOR_USER_SCORE not in", values, "supervisorUserScore");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUPERVISOR_USER_SCORE between", value1, value2, "supervisorUserScore");
            return (Criteria) this;
        }

        public Criteria andSupervisorUserScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUPERVISOR_USER_SCORE not between", value1, value2, "supervisorUserScore");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreIsNull() {
            addCriterion("CENTER_SUPERVISOR_SCORE is null");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreIsNotNull() {
            addCriterion("CENTER_SUPERVISOR_SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreEqualTo(BigDecimal value) {
            addCriterion("CENTER_SUPERVISOR_SCORE =", value, "centerSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreNotEqualTo(BigDecimal value) {
            addCriterion("CENTER_SUPERVISOR_SCORE <>", value, "centerSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreGreaterThan(BigDecimal value) {
            addCriterion("CENTER_SUPERVISOR_SCORE >", value, "centerSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CENTER_SUPERVISOR_SCORE >=", value, "centerSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreLessThan(BigDecimal value) {
            addCriterion("CENTER_SUPERVISOR_SCORE <", value, "centerSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CENTER_SUPERVISOR_SCORE <=", value, "centerSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreIn(List<BigDecimal> values) {
            addCriterion("CENTER_SUPERVISOR_SCORE in", values, "centerSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreNotIn(List<BigDecimal> values) {
            addCriterion("CENTER_SUPERVISOR_SCORE not in", values, "centerSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CENTER_SUPERVISOR_SCORE between", value1, value2, "centerSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andCenterSupervisorScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CENTER_SUPERVISOR_SCORE not between", value1, value2, "centerSupervisorScore");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresIsNull() {
            addCriterion("SUPERVISOR_TOTAL_SCORES is null");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresIsNotNull() {
            addCriterion("SUPERVISOR_TOTAL_SCORES is not null");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresEqualTo(BigDecimal value) {
            addCriterion("SUPERVISOR_TOTAL_SCORES =", value, "supervisorTotalScores");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresNotEqualTo(BigDecimal value) {
            addCriterion("SUPERVISOR_TOTAL_SCORES <>", value, "supervisorTotalScores");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresGreaterThan(BigDecimal value) {
            addCriterion("SUPERVISOR_TOTAL_SCORES >", value, "supervisorTotalScores");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUPERVISOR_TOTAL_SCORES >=", value, "supervisorTotalScores");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresLessThan(BigDecimal value) {
            addCriterion("SUPERVISOR_TOTAL_SCORES <", value, "supervisorTotalScores");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUPERVISOR_TOTAL_SCORES <=", value, "supervisorTotalScores");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresIn(List<BigDecimal> values) {
            addCriterion("SUPERVISOR_TOTAL_SCORES in", values, "supervisorTotalScores");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresNotIn(List<BigDecimal> values) {
            addCriterion("SUPERVISOR_TOTAL_SCORES not in", values, "supervisorTotalScores");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUPERVISOR_TOTAL_SCORES between", value1, value2, "supervisorTotalScores");
            return (Criteria) this;
        }

        public Criteria andSupervisorTotalScoresNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUPERVISOR_TOTAL_SCORES not between", value1, value2, "supervisorTotalScores");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoIsNull() {
            addCriterion("SUPERVISOR_IS_DO is null");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoIsNotNull() {
            addCriterion("SUPERVISOR_IS_DO is not null");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoEqualTo(String value) {
            addCriterion("SUPERVISOR_IS_DO =", value, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoNotEqualTo(String value) {
            addCriterion("SUPERVISOR_IS_DO <>", value, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoGreaterThan(String value) {
            addCriterion("SUPERVISOR_IS_DO >", value, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoGreaterThanOrEqualTo(String value) {
            addCriterion("SUPERVISOR_IS_DO >=", value, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoLessThan(String value) {
            addCriterion("SUPERVISOR_IS_DO <", value, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoLessThanOrEqualTo(String value) {
            addCriterion("SUPERVISOR_IS_DO <=", value, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoLike(String value) {
            addCriterion("SUPERVISOR_IS_DO like", value, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoNotLike(String value) {
            addCriterion("SUPERVISOR_IS_DO not like", value, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoIn(List<String> values) {
            addCriterion("SUPERVISOR_IS_DO in", values, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoNotIn(List<String> values) {
            addCriterion("SUPERVISOR_IS_DO not in", values, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoBetween(String value1, String value2) {
            addCriterion("SUPERVISOR_IS_DO between", value1, value2, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorIsDoNotBetween(String value1, String value2) {
            addCriterion("SUPERVISOR_IS_DO not between", value1, value2, "supervisorIsDo");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeIsNull() {
            addCriterion("SUPERVISOR_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeIsNotNull() {
            addCriterion("SUPERVISOR_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeEqualTo(Date value) {
            addCriterion("SUPERVISOR_TIME =", value, "supervisorTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeNotEqualTo(Date value) {
            addCriterion("SUPERVISOR_TIME <>", value, "supervisorTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeGreaterThan(Date value) {
            addCriterion("SUPERVISOR_TIME >", value, "supervisorTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SUPERVISOR_TIME >=", value, "supervisorTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeLessThan(Date value) {
            addCriterion("SUPERVISOR_TIME <", value, "supervisorTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeLessThanOrEqualTo(Date value) {
            addCriterion("SUPERVISOR_TIME <=", value, "supervisorTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeIn(List<Date> values) {
            addCriterion("SUPERVISOR_TIME in", values, "supervisorTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeNotIn(List<Date> values) {
            addCriterion("SUPERVISOR_TIME not in", values, "supervisorTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeBetween(Date value1, Date value2) {
            addCriterion("SUPERVISOR_TIME between", value1, value2, "supervisorTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorTimeNotBetween(Date value1, Date value2) {
            addCriterion("SUPERVISOR_TIME not between", value1, value2, "supervisorTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeIsNull() {
            addCriterion("SUPERVISOR_UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeIsNotNull() {
            addCriterion("SUPERVISOR_UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeEqualTo(Date value) {
            addCriterion("SUPERVISOR_UPDATE_TIME =", value, "supervisorUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeNotEqualTo(Date value) {
            addCriterion("SUPERVISOR_UPDATE_TIME <>", value, "supervisorUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeGreaterThan(Date value) {
            addCriterion("SUPERVISOR_UPDATE_TIME >", value, "supervisorUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SUPERVISOR_UPDATE_TIME >=", value, "supervisorUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeLessThan(Date value) {
            addCriterion("SUPERVISOR_UPDATE_TIME <", value, "supervisorUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("SUPERVISOR_UPDATE_TIME <=", value, "supervisorUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeIn(List<Date> values) {
            addCriterion("SUPERVISOR_UPDATE_TIME in", values, "supervisorUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeNotIn(List<Date> values) {
            addCriterion("SUPERVISOR_UPDATE_TIME not in", values, "supervisorUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("SUPERVISOR_UPDATE_TIME between", value1, value2, "supervisorUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSupervisorUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("SUPERVISOR_UPDATE_TIME not between", value1, value2, "supervisorUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table score_order
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table score_order
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}