package com.example.demo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ScoreOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.COMPANY_ID
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.DEL
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.BESORDER_ID
     *
     * @mbggenerated
     */
    private Long besorderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.PROJECT_ID
     *
     * @mbggenerated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.USER_ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.FOREMAN_IS_DISCUSS
     *
     * @mbggenerated
     */
    private String foremanIsDiscuss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.FOREMAN_NUM
     *
     * @mbggenerated
     */
    private Integer foremanNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.FOREMAN_USER_SCORE
     *
     * @mbggenerated
     */
    private BigDecimal foremanUserScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.FOREMAN_SUPERVISOR_SCORE
     *
     * @mbggenerated
     */
    private BigDecimal foremanSupervisorScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.CENTER_FOREMAN_SCORE
     *
     * @mbggenerated
     */
    private BigDecimal centerForemanScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.FOREMAN_TOTAL_SCORES
     *
     * @mbggenerated
     */
    private BigDecimal foremanTotalScores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.FOREMAN_IS_DO
     *
     * @mbggenerated
     */
    private String foremanIsDo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.FOREMAN_TIME
     *
     * @mbggenerated
     */
    private Date foremanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.FOREMAN_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date foremanUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.DESIGN_IS_DISCUSS
     *
     * @mbggenerated
     */
    private String designIsDiscuss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.DESIGN_NUM
     *
     * @mbggenerated
     */
    private Integer designNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.DESIGN_USER_SCORE
     *
     * @mbggenerated
     */
    private BigDecimal designUserScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.DESIGN_SUPERVISOR_SCORE
     *
     * @mbggenerated
     */
    private BigDecimal designSupervisorScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.DESIGN_CENTER_SCORE
     *
     * @mbggenerated
     */
    private BigDecimal designCenterScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.DESIGN_TOTAL_SCORES
     *
     * @mbggenerated
     */
    private BigDecimal designTotalScores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.DESIGN_IS_CENTER_DO
     *
     * @mbggenerated
     */
    private String designIsCenterDo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.DESIGN_TIME
     *
     * @mbggenerated
     */
    private Date designTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.DESIGN_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date designUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.REMARK1
     *
     * @mbggenerated
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.REMARK2
     *
     * @mbggenerated
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.SUPERVISOR_IS_DISCUSS
     *
     * @mbggenerated
     */
    private String supervisorIsDiscuss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.SUPERVISOR_NUM
     *
     * @mbggenerated
     */
    private Integer supervisorNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.SUPERVISOR_USER_SCORE
     *
     * @mbggenerated
     */
    private BigDecimal supervisorUserScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.CENTER_SUPERVISOR_SCORE
     *
     * @mbggenerated
     */
    private BigDecimal centerSupervisorScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.SUPERVISOR_TOTAL_SCORES
     *
     * @mbggenerated
     */
    private BigDecimal supervisorTotalScores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.SUPERVISOR_IS_DO
     *
     * @mbggenerated
     */
    private String supervisorIsDo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.SUPERVISOR_TIME
     *
     * @mbggenerated
     */
    private Date supervisorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_order.SUPERVISOR_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date supervisorUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.ID
     *
     * @return the value of score_order.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.ID
     *
     * @param id the value for score_order.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.VERSION
     *
     * @return the value of score_order.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.VERSION
     *
     * @param version the value for score_order.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.COMPANY_ID
     *
     * @return the value of score_order.COMPANY_ID
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.COMPANY_ID
     *
     * @param companyId the value for score_order.COMPANY_ID
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.DEL
     *
     * @return the value of score_order.DEL
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.DEL
     *
     * @param del the value for score_order.DEL
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.CREATE_TIME
     *
     * @return the value of score_order.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.CREATE_TIME
     *
     * @param createTime the value for score_order.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.UPDATE_TIME
     *
     * @return the value of score_order.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.UPDATE_TIME
     *
     * @param updateTime the value for score_order.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.BESORDER_ID
     *
     * @return the value of score_order.BESORDER_ID
     *
     * @mbggenerated
     */
    public Long getBesorderId() {
        return besorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.BESORDER_ID
     *
     * @param besorderId the value for score_order.BESORDER_ID
     *
     * @mbggenerated
     */
    public void setBesorderId(Long besorderId) {
        this.besorderId = besorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.PROJECT_ID
     *
     * @return the value of score_order.PROJECT_ID
     *
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.PROJECT_ID
     *
     * @param projectId the value for score_order.PROJECT_ID
     *
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.USER_ID
     *
     * @return the value of score_order.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.USER_ID
     *
     * @param userId the value for score_order.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.CITY
     *
     * @return the value of score_order.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.CITY
     *
     * @param city the value for score_order.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.FOREMAN_IS_DISCUSS
     *
     * @return the value of score_order.FOREMAN_IS_DISCUSS
     *
     * @mbggenerated
     */
    public String getForemanIsDiscuss() {
        return foremanIsDiscuss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.FOREMAN_IS_DISCUSS
     *
     * @param foremanIsDiscuss the value for score_order.FOREMAN_IS_DISCUSS
     *
     * @mbggenerated
     */
    public void setForemanIsDiscuss(String foremanIsDiscuss) {
        this.foremanIsDiscuss = foremanIsDiscuss == null ? null : foremanIsDiscuss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.FOREMAN_NUM
     *
     * @return the value of score_order.FOREMAN_NUM
     *
     * @mbggenerated
     */
    public Integer getForemanNum() {
        return foremanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.FOREMAN_NUM
     *
     * @param foremanNum the value for score_order.FOREMAN_NUM
     *
     * @mbggenerated
     */
    public void setForemanNum(Integer foremanNum) {
        this.foremanNum = foremanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.FOREMAN_USER_SCORE
     *
     * @return the value of score_order.FOREMAN_USER_SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getForemanUserScore() {
        return foremanUserScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.FOREMAN_USER_SCORE
     *
     * @param foremanUserScore the value for score_order.FOREMAN_USER_SCORE
     *
     * @mbggenerated
     */
    public void setForemanUserScore(BigDecimal foremanUserScore) {
        this.foremanUserScore = foremanUserScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.FOREMAN_SUPERVISOR_SCORE
     *
     * @return the value of score_order.FOREMAN_SUPERVISOR_SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getForemanSupervisorScore() {
        return foremanSupervisorScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.FOREMAN_SUPERVISOR_SCORE
     *
     * @param foremanSupervisorScore the value for score_order.FOREMAN_SUPERVISOR_SCORE
     *
     * @mbggenerated
     */
    public void setForemanSupervisorScore(BigDecimal foremanSupervisorScore) {
        this.foremanSupervisorScore = foremanSupervisorScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.CENTER_FOREMAN_SCORE
     *
     * @return the value of score_order.CENTER_FOREMAN_SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getCenterForemanScore() {
        return centerForemanScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.CENTER_FOREMAN_SCORE
     *
     * @param centerForemanScore the value for score_order.CENTER_FOREMAN_SCORE
     *
     * @mbggenerated
     */
    public void setCenterForemanScore(BigDecimal centerForemanScore) {
        this.centerForemanScore = centerForemanScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.FOREMAN_TOTAL_SCORES
     *
     * @return the value of score_order.FOREMAN_TOTAL_SCORES
     *
     * @mbggenerated
     */
    public BigDecimal getForemanTotalScores() {
        return foremanTotalScores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.FOREMAN_TOTAL_SCORES
     *
     * @param foremanTotalScores the value for score_order.FOREMAN_TOTAL_SCORES
     *
     * @mbggenerated
     */
    public void setForemanTotalScores(BigDecimal foremanTotalScores) {
        this.foremanTotalScores = foremanTotalScores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.FOREMAN_IS_DO
     *
     * @return the value of score_order.FOREMAN_IS_DO
     *
     * @mbggenerated
     */
    public String getForemanIsDo() {
        return foremanIsDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.FOREMAN_IS_DO
     *
     * @param foremanIsDo the value for score_order.FOREMAN_IS_DO
     *
     * @mbggenerated
     */
    public void setForemanIsDo(String foremanIsDo) {
        this.foremanIsDo = foremanIsDo == null ? null : foremanIsDo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.FOREMAN_TIME
     *
     * @return the value of score_order.FOREMAN_TIME
     *
     * @mbggenerated
     */
    public Date getForemanTime() {
        return foremanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.FOREMAN_TIME
     *
     * @param foremanTime the value for score_order.FOREMAN_TIME
     *
     * @mbggenerated
     */
    public void setForemanTime(Date foremanTime) {
        this.foremanTime = foremanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.FOREMAN_UPDATE_TIME
     *
     * @return the value of score_order.FOREMAN_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getForemanUpdateTime() {
        return foremanUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.FOREMAN_UPDATE_TIME
     *
     * @param foremanUpdateTime the value for score_order.FOREMAN_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setForemanUpdateTime(Date foremanUpdateTime) {
        this.foremanUpdateTime = foremanUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.DESIGN_IS_DISCUSS
     *
     * @return the value of score_order.DESIGN_IS_DISCUSS
     *
     * @mbggenerated
     */
    public String getDesignIsDiscuss() {
        return designIsDiscuss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.DESIGN_IS_DISCUSS
     *
     * @param designIsDiscuss the value for score_order.DESIGN_IS_DISCUSS
     *
     * @mbggenerated
     */
    public void setDesignIsDiscuss(String designIsDiscuss) {
        this.designIsDiscuss = designIsDiscuss == null ? null : designIsDiscuss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.DESIGN_NUM
     *
     * @return the value of score_order.DESIGN_NUM
     *
     * @mbggenerated
     */
    public Integer getDesignNum() {
        return designNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.DESIGN_NUM
     *
     * @param designNum the value for score_order.DESIGN_NUM
     *
     * @mbggenerated
     */
    public void setDesignNum(Integer designNum) {
        this.designNum = designNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.DESIGN_USER_SCORE
     *
     * @return the value of score_order.DESIGN_USER_SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getDesignUserScore() {
        return designUserScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.DESIGN_USER_SCORE
     *
     * @param designUserScore the value for score_order.DESIGN_USER_SCORE
     *
     * @mbggenerated
     */
    public void setDesignUserScore(BigDecimal designUserScore) {
        this.designUserScore = designUserScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.DESIGN_SUPERVISOR_SCORE
     *
     * @return the value of score_order.DESIGN_SUPERVISOR_SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getDesignSupervisorScore() {
        return designSupervisorScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.DESIGN_SUPERVISOR_SCORE
     *
     * @param designSupervisorScore the value for score_order.DESIGN_SUPERVISOR_SCORE
     *
     * @mbggenerated
     */
    public void setDesignSupervisorScore(BigDecimal designSupervisorScore) {
        this.designSupervisorScore = designSupervisorScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.DESIGN_CENTER_SCORE
     *
     * @return the value of score_order.DESIGN_CENTER_SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getDesignCenterScore() {
        return designCenterScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.DESIGN_CENTER_SCORE
     *
     * @param designCenterScore the value for score_order.DESIGN_CENTER_SCORE
     *
     * @mbggenerated
     */
    public void setDesignCenterScore(BigDecimal designCenterScore) {
        this.designCenterScore = designCenterScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.DESIGN_TOTAL_SCORES
     *
     * @return the value of score_order.DESIGN_TOTAL_SCORES
     *
     * @mbggenerated
     */
    public BigDecimal getDesignTotalScores() {
        return designTotalScores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.DESIGN_TOTAL_SCORES
     *
     * @param designTotalScores the value for score_order.DESIGN_TOTAL_SCORES
     *
     * @mbggenerated
     */
    public void setDesignTotalScores(BigDecimal designTotalScores) {
        this.designTotalScores = designTotalScores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.DESIGN_IS_CENTER_DO
     *
     * @return the value of score_order.DESIGN_IS_CENTER_DO
     *
     * @mbggenerated
     */
    public String getDesignIsCenterDo() {
        return designIsCenterDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.DESIGN_IS_CENTER_DO
     *
     * @param designIsCenterDo the value for score_order.DESIGN_IS_CENTER_DO
     *
     * @mbggenerated
     */
    public void setDesignIsCenterDo(String designIsCenterDo) {
        this.designIsCenterDo = designIsCenterDo == null ? null : designIsCenterDo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.DESIGN_TIME
     *
     * @return the value of score_order.DESIGN_TIME
     *
     * @mbggenerated
     */
    public Date getDesignTime() {
        return designTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.DESIGN_TIME
     *
     * @param designTime the value for score_order.DESIGN_TIME
     *
     * @mbggenerated
     */
    public void setDesignTime(Date designTime) {
        this.designTime = designTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.DESIGN_UPDATE_TIME
     *
     * @return the value of score_order.DESIGN_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getDesignUpdateTime() {
        return designUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.DESIGN_UPDATE_TIME
     *
     * @param designUpdateTime the value for score_order.DESIGN_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setDesignUpdateTime(Date designUpdateTime) {
        this.designUpdateTime = designUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.REMARK1
     *
     * @return the value of score_order.REMARK1
     *
     * @mbggenerated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.REMARK1
     *
     * @param remark1 the value for score_order.REMARK1
     *
     * @mbggenerated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.REMARK2
     *
     * @return the value of score_order.REMARK2
     *
     * @mbggenerated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.REMARK2
     *
     * @param remark2 the value for score_order.REMARK2
     *
     * @mbggenerated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.SUPERVISOR_IS_DISCUSS
     *
     * @return the value of score_order.SUPERVISOR_IS_DISCUSS
     *
     * @mbggenerated
     */
    public String getSupervisorIsDiscuss() {
        return supervisorIsDiscuss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.SUPERVISOR_IS_DISCUSS
     *
     * @param supervisorIsDiscuss the value for score_order.SUPERVISOR_IS_DISCUSS
     *
     * @mbggenerated
     */
    public void setSupervisorIsDiscuss(String supervisorIsDiscuss) {
        this.supervisorIsDiscuss = supervisorIsDiscuss == null ? null : supervisorIsDiscuss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.SUPERVISOR_NUM
     *
     * @return the value of score_order.SUPERVISOR_NUM
     *
     * @mbggenerated
     */
    public Integer getSupervisorNum() {
        return supervisorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.SUPERVISOR_NUM
     *
     * @param supervisorNum the value for score_order.SUPERVISOR_NUM
     *
     * @mbggenerated
     */
    public void setSupervisorNum(Integer supervisorNum) {
        this.supervisorNum = supervisorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.SUPERVISOR_USER_SCORE
     *
     * @return the value of score_order.SUPERVISOR_USER_SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getSupervisorUserScore() {
        return supervisorUserScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.SUPERVISOR_USER_SCORE
     *
     * @param supervisorUserScore the value for score_order.SUPERVISOR_USER_SCORE
     *
     * @mbggenerated
     */
    public void setSupervisorUserScore(BigDecimal supervisorUserScore) {
        this.supervisorUserScore = supervisorUserScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.CENTER_SUPERVISOR_SCORE
     *
     * @return the value of score_order.CENTER_SUPERVISOR_SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getCenterSupervisorScore() {
        return centerSupervisorScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.CENTER_SUPERVISOR_SCORE
     *
     * @param centerSupervisorScore the value for score_order.CENTER_SUPERVISOR_SCORE
     *
     * @mbggenerated
     */
    public void setCenterSupervisorScore(BigDecimal centerSupervisorScore) {
        this.centerSupervisorScore = centerSupervisorScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.SUPERVISOR_TOTAL_SCORES
     *
     * @return the value of score_order.SUPERVISOR_TOTAL_SCORES
     *
     * @mbggenerated
     */
    public BigDecimal getSupervisorTotalScores() {
        return supervisorTotalScores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.SUPERVISOR_TOTAL_SCORES
     *
     * @param supervisorTotalScores the value for score_order.SUPERVISOR_TOTAL_SCORES
     *
     * @mbggenerated
     */
    public void setSupervisorTotalScores(BigDecimal supervisorTotalScores) {
        this.supervisorTotalScores = supervisorTotalScores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.SUPERVISOR_IS_DO
     *
     * @return the value of score_order.SUPERVISOR_IS_DO
     *
     * @mbggenerated
     */
    public String getSupervisorIsDo() {
        return supervisorIsDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.SUPERVISOR_IS_DO
     *
     * @param supervisorIsDo the value for score_order.SUPERVISOR_IS_DO
     *
     * @mbggenerated
     */
    public void setSupervisorIsDo(String supervisorIsDo) {
        this.supervisorIsDo = supervisorIsDo == null ? null : supervisorIsDo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.SUPERVISOR_TIME
     *
     * @return the value of score_order.SUPERVISOR_TIME
     *
     * @mbggenerated
     */
    public Date getSupervisorTime() {
        return supervisorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.SUPERVISOR_TIME
     *
     * @param supervisorTime the value for score_order.SUPERVISOR_TIME
     *
     * @mbggenerated
     */
    public void setSupervisorTime(Date supervisorTime) {
        this.supervisorTime = supervisorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_order.SUPERVISOR_UPDATE_TIME
     *
     * @return the value of score_order.SUPERVISOR_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getSupervisorUpdateTime() {
        return supervisorUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_order.SUPERVISOR_UPDATE_TIME
     *
     * @param supervisorUpdateTime the value for score_order.SUPERVISOR_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setSupervisorUpdateTime(Date supervisorUpdateTime) {
        this.supervisorUpdateTime = supervisorUpdateTime;
    }
}